name: Build and Run Docker

on:
  push:
    branches:
      - main

jobs:
  build_docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker
        run: docker build -t go-cicd .
