name: Deploy to Railway Dev Environment

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and Deploy
        run: go run deploy.go
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}
