name: Deploy to Scalingo

on:
  push:
    branches:
      - main  # Sesuaikan dengan cabang Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21  # Sesuaikan dengan versi Go Anda

      - name: Build and Deploy
        run: |
          go build -o myapp
          curl -O https://cli-dl.scalingo.io/install && sh ./install
          scalingo login $SCALINGO_API_TOKEN scalingo@example.com
          scalingo -a myapp deploy

