name: Deploy to Scalingo

on:
  push:
    branches:
      - main  # Sesuaikan dengan cabang Anda

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.2

      - name: Build
        run: go build -o myapp

      - name: Install Scalingo CLI
        run: |
          curl -O https://cli-dl.scalingo.com/install && bash install

      - name: Login to Scalingo
        run: |
          scalingo login $SCALINGO_API_TOKEN scalingo@example.com

      - name: Deploy to Scalingo
        run: scalingo -a myapp deploy
