name: Docker Build and Publish

on:
  push:
    branches:
      - main # Atur sesuai dengan branch yang Anda inginkan

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-docker-image .

      - name: Push Docker image
        run: docker push my-docker-image
